import * as React from "react";
import { styled } from "@mui/material/styles";
import Grid from "@mui/material/Grid";
import Paper from "@mui/material/Paper";
import Box from "@mui/material/Box";

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));

export default function Grids() {
  return (
    <Box sx={{ width: "100%" }}>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
        {itemData.map((item) => (
          <Grid item xs={4}>
            <Item>{item.name}</Item>
          </Grid>
        ))}
      </Grid>
    </Box>
  );
}

const itemData = [
  { name: "3A Homes & Construction Pvt. Ltd." },
  { name: "Abroadshiksha.com" },
  { name: "Acadecraft Pvt. Ltd." },
  { name: "ACCYS" },
  { name: "ACME CLEANTECH SOLUTION LTD." },
  { name: "AD WORLDWIDE TECH." },
  { name: "ADECCO INDIA" },
  { name: "Adeptia India Pvt. Ltd." },
  { name: "Aftech Systems Pvt. Ltd." },
  { name: "AGS Transact Technologies Ltd." },
  { name: "Ahresty India Pvt. Ltd." },
  { name: "AIM India" },
  { name: "AIRSOFT" },
  { name: "Airtel" },
  { name: "Akzo Nobel" },
  { name: "ALANKIT INSURANCE LTD." },
  { name: "All e Technologies Pvt. Ltd." },
  { name: "Allied Structural Engneering" },
  { name: "Alphabyte" },
  { name: "Amazon Development Centre (India) Pvt. Ltd." },
  { name: "Ameriprise Financials (Off Campus)" },
  { name: "Amiga Informatics Inc." },
  { name: "Amosta Solutions Pvt. Ltd." },
  { name: "Anchor Electricals Pvt. Ltd." },
  { name: "Anjani Technoplast Ltd." },
  { name: "Aon Hewitt" },
  { name: "Apar Technologies Pvt. Ltd." },
  { name: "Apar Technology Pvt. Ltd." },
  { name: "Apollo Tyres Ltd." },
  { name: "App Squadz Technologies Pvt. Ltd." },
  { name: "APPLANE SOLUTION (Daffodil) " },
  { name: "Aptara Corp." },
  { name: "ARISE INDIA LIMITED" },
  { name: "Aryama Soft Services Pvt. Ltd." },
  { name: "Asahi India Glass Ltd." },
  { name: "ATC TELECOM" },
  { name: "Atlas Cycles Ltd." },
  { name: "Axis Bank" },
  { name: "Bajaj Motors Ltd." },
  { name: "Bajaj Sons Ltd." },
  { name: "Basware" },
  { name: "Beaver Systems" },
  { name: "Berger Paints India Ltd." },
  { name: "Bhilwara Infotechnology Ltd." },
  { name: "Bhilwara Technologies Limited" },
  { name: "Bhiraniya Technologies Pvt. Ltd." },
  { name: "BINARY TECHNOSYS" },
  { name: "Bionic Group" },
  { name: "Bluegape Lifestyle Pvt. Ltd." },
  { name: "BMR Advisors" },
  { name: "C-zentrix" },
  { name: "Cadapult Technologies (Techsavvy)" },
  { name: "Caparo Maruti Ltd." },
  { name: "CAPITALVIA!" },
  { name: "CappitalVia Global Research Ltd." },
  { name: "Carbon Software Solution" },
  { name: "CeaseFire Industries Ltd." },
  { name: "CINIF Technologies Ltd." },
  { name: "CLUB MAHINDRA" },
  { name: "Collebara Technology Pvt. Ltd." },
  { name: "Compro Technologies" },
  { name: "Compton Computers Pvt. Ltd." },
  { name: "Computronics Systems India Pvt. Ltd." },
  { name: "Crescent Worldwide Services (Off Campus)" },
  { name: "Cryptographic IT Solutions" },
  { name: "CSS CORP Pvt. Ltd." },
  { name: "CYNOTECK TECHNOLOGY SOLUTIONS PVT. LTD." },
  { name: "D-TAB SAFETY SECURITY SYSTEMS PVT. LTD." },
  { name: "Daffodil Software Limited." },
  { name: "Data64 Cyber Solutions (P) Ltd." },
  { name: "Debbas Prime Ltd." },
  { name: "Decathlon Sports" },
  { name: "Denave India Pvt. Ltd. (Airtel)" },
  { name: "Denso Pvt. Ltd." },
  { name: "DEUTSCHE BANK" },
  { name: "DigiCall Technologies Pvt. Ltd." },
  { name: "Directi Internet Solutions Pvt. Ltd." },
  { name: "DIVERSE LYNX INDIA PVT. LTD." },
  { name: "Duratuf Glass Industries (P) Ltd." },
  { name: "E P I C Research PVT. LTD." },
  { name: "Eapro Global Ltd." },
  { name: "EASY POLICY.COM " },
  { name: "EBZ Systek India Pvt. Ltd. (Off Campus)" },
  { name: "eClerx Services Limited" },
  { name: "EKO India Financial Services Pvt. Ltd." },
  { name: "ELI RESEARCH INDIA PVT. LTD." },
  { name: "Emicon Advisory LLP" },
  { name: "Emicon Advisory Services" },
  { name: "Emson Gears" },
  { name: "Eninov Systems" },
  { name: "ePeople Technologies Inc" },
  { name: "Epic Research Pvt. Ltd." },
  { name: "Era Infra Engg. Ltd. " },
  { name: "ERD Technologies Pvt. Ltd." },
  { name: "ERICSSON" },
  { name: "Essline Engineers and Consultants Pvt. Ltd." },
  { name: "Eternity Agencies Pvt. Ltd." },
  { name: "Everest Industries Ltd." },
  { name: "Exide Industries Ltd." },
  { name: "Felicity Group" },
  { name: "Financial Software And Systems" },
  { name: "Finoit Technologies (I) Pvt. Ltd." },
  { name: "FLIPKART" },
  { name: "Focus Academy" },
  { name: "FOCUS ENERGY LTD." },
  { name: "Forace Polymers" },
  { name: "Franconnect" },
  { name: "FranConnect India Software" },
  { name: "Frog Cellsat Ltd." },
  { name: "Fusion Microfinance Pvt.Ltd." },
  { name: "Fusion Techware" },
  { name: "Futureistic Simplified Computing Pvt. Ltd." },
  { name: "Gannon dunkerley" },
  { name: "Gauri Switch Gear India Pvt. Ltd." },
  { name: "Genesys International Corporation Ltd" },
  { name: "Genexis Business Process Services Pvt. Ltd." },
  { name: "Genpact" },
  { name: "Genus Power Infrastructers Ltd." },
  { name: "GIL" },
  { name: "Global Engineering Corporation" },
  { name: "Global Step" },
  { name: "Gold Plus Glass Industry Ltd." },
  { name: "Green Tree" },
  { name: "Groupware Technologies" },
  { name: "Gruner India Pvt. Ltd. (Off Campus)" },
  { name: "Guru Nanak Forging Pvt. Ltd." },
  { name: "Gusty Engineering Pvt. Ltd." },
  { name: "Harit Dharaa Projects (P) Ltd." },
  { name: "HCL (BPO)" },
  { name: "HCL Technologies Ltd. (HCL BSERV)" },
  { name: "HDFC Bank" },
  { name: "Hero Cycles" },
  { name: "Hettich India Pvt. Ltd." },
  { name: "Him Imperial Auto Glass Works" },
  { name: "Hitech Enviro Engineers & Consultants Pvt. Ltd." },
  { name: "Hopes Group" },
  { name: "Housing.com " },
  { name: "HP Enterprises India Pvt. Ltd. (Off Campus)" },
  { name: "HT MEDIA LTD." },
  { name: "Hydrodfab Technomech India Pvt. Ltd." },
  { name: "ICE - Balaji Telefilms (Off Campus)" },
  { name: "Impelsys" },
  { name: "India Infoline Housing Finance" },
  { name: "India Shelter Finance Corporation Ltd." },
  { name: "IndiaMart.com" },
  { name: "INDIAN ARMY" },
  { name: "Indusind Bank" },
  { name: "INNOEYE TECHNOLOGIES" },
  { name: "Innoeye Technologies Pvt. Ltd." },
  { name: "InnovationM" },
  { name: "Innovative Design Tech. Pvt. Ltd." },
  { name: "Investors Clinic Infratech Pvt. Ltd." },
  { name: "iSearch Solution Pvt. Ltd." },
  { name: "J K TECHNOSOFT" },
  { name: "JAGBROS" },
  { name: "JANALAKSHMI FINANCIAL SERVICES" },
  { name: "Jangid Motors India Pvt. Ltd. " },
  { name: "Jaro Educaion" },
  { name: "Jay Ace Technologies Ltd." },
  { name: "JEEVANSATHI.COM" },
  { name: "Jet Age Garage Equipments" },
  { name: "JK Cement Ltd." },
  { name: "JK Machines" },
  { name: "John Deere India Pvt. Ltd." },
  { name: "Johnson Lifts Pvt. Ltd. (Off Campus)" },
  { name: "Josh Technology Group" },
  { name: "JustDial" },
  { name: "Kellton Tech Solutions" },
  { name: "KNOWLEDGE PODIUM" },
  { name: "KPIT Technologies Ltd." },
  { name: "Krishna Maruti" },
  { name: "Lares Softech Pvt. Ltd." },
  { name: "Lattice Bridge Infotech" },
  { name: "LeewayHertz" },
  { name: "Lions Workforce Solutions (I) Pvt. Ltd." },
  { name: "Live Satyam Tech" },
  { name: "Live Technician.com" },
  { name: "Logic ERP Solutions Pvt. Ltd." },
  { name: "Madhyam.com (Off Campus)" },
  { name: "Mahindra & Mahindra" },
  { name: "Maintec Technologies Pvt. Ltd." },
  { name: "Makino Automotive" },
  { name: "Malhotra Rubbers Ltd." },
  { name: "Mangla Tubes Pvt. Ltd." },
  { name: "MAX Group of Company" },
  { name: "MGI INFRA PVT. LTD" },
  { name: "Micro Root Poc Technology Pvt. Ltd." },
  { name: "Micromax" },
  { name: "Mikuni India Pvt. Ltd. (For old students)" },
  { name: "Milestone Gear Pvt. Ltd." },
  { name: "Mirage Ceramics" },
  { name: "Modern Automotives Ltd." },
  { name: "Modern Steel Ltd." },
  { name: "Montage Enterprises Pvt. Ltd." },
  { name: "Motherson Molds & Diecasting Ltd." },
  { name: "Mphasis Limited" },
  { name: "Mr. Med" },
  { name: "Munjal Kiriu Industries (P) Ltd." },
  { name: "My Operator" },
  { name: "Myzeal IT Solution Pvt. Ltd." },
  { name: "NAUKRI.COM - JEEVANSATHI.COM " },
  { name: "Nestkeys" },
  { name: "New Technology Research Software Services Pvt. Ltd." },
  { name: "NIIT Technologies" },
  { name: "Octaware Systems" },
  { name: "OMNIGLOBE INFORMATION TECHNOLOGIES" },
  { name: "ONICRA CREDIT INFORMATION COMPANY LTD. " },
  { name: "Oodles Technologies." },
  { name: "Oppo Mobiles" },
  { name: "Optiemus Electronics Ltd." },
  { name: "PANDAJE GROUP " },
  { name: "Patanjali" },
  { name: "PC Technology Pvt. Ltd." },
  { name: "Peerless System" },
  { name: "Pellet Energy Systems Pvt. Ltd." },
  { name: "People Specialist Staffing Services" },
  { name: "PEPSICO" },
  { name: "PK Industries Pvt. Ltd." },
  { name: "Pritam International Pvt. Ltd." },
  { name: "Proptiger.com" },
  { name: "QUALITAS GLOBAL" },
  { name: "Questa Global Pvt. Ltd." },
  { name: "Quick Heal Technologies Ltd." },
  { name: "R Systems International Pvt. Ltd." },
  { name: "Raas Capital" },
  { name: "RAILTECH" },
  { name: "Relaxo Footwear Ltd." },
  { name: "Reliance Jio" },
  { name: "Religare Securities Ltd." },
  { name: "RETAILON" },
  { name: "RGF Professional Recruitment" },
  { name: "Robosapiens Technologies Pvt. Ltd. / ZoikMail" },
  { name: "Roop Automotive Ltd." },
  { name: "Rose IT Solutions" },
  { name: "Royal SR Engineering Corporation." },
  { name: "Rubico IT Pvt. Ltd." },
  { name: "S2 INFOTECH" },
  { name: "Safe Towers Pvt. Ltd." },
  { name: "SAG INFOTECH" },
  { name: "Sage Publications Pvt. Ltd." },
  { name: "Sandhar Technology Ltd." },
  { name: "Saransh Group" },
  { name: "Satyam Auto Pvt. Ltd." },
  { name: "Satyam Software Solutions Pvt. Ltd." },
  { name: "Serava Solutions" },
  { name: "SERCO GLOBAL SERVICES" },
  { name: "Shahi Exports Pvt. Ltd." },
  { name: "Shiv Shakti Float Glass Pvt. Ltd." },
  { name: "Shree Swastik Tuff Glass LLP" },
  { name: "Shree Swatik Tuff Glass Llp" },
  { name: "SHRIRAM VERITECH SOLUTIONS PVT. LTD." },
  { name: "Sigma ITES" },
  { name: "Silverpeak Global Pvt. Ltd." },
  { name: "SKF India Ltd." },
  { name: "SmartData Enterprises" },
  { name: "Smartprix Technologies" },
  { name: "Smashing Geeks" },
  { name: "SNL Financial " },
  { name: "SOURCEKEY MEDIA PVT LTD" },
  { name: "Space Technology & Education Pvt. Ltd." },
  { name: "Spatial Geotech Pvt. Ltd." },
  { name: "Spice Digital Ltd." },
  { name: "Spray Engineering Devices Ltd." },
  { name: "STARTBEANS CONSULTING PVT. LTD. " },
  { name: "Studymate Online" },
  { name: "Successive Softwares" },
  { name: "Sudhir Power Ltd." },
  { name: "Sunbeam Auto Pvt. Ltd." },
  { name: "SunBeam Pvt. Ltd." },
  { name: "Sunmax Auto Engg. Pvt. Ltd." },
  { name: "Surabhi Engineers Ltd." },
  { name: "SYNTELL" },
  { name: "Syscom Softech Pvt. Ltd." },
  { name: "TACKY MINDS" },
  { name: "Tech Mahindra" },
  { name: "Tech Savvy" },
  { name: "Teleperformance Ltd." },
  { name: "Thales Group" },
  { name: "Think & Learn" },
  { name: "Thoughts2Binary Consulting & Solutions LLP." },
  { name: "TII INDIA Ltd." },
  { name: "TO THE NEW DIGITAL (INTELLIGRAPE SOFTWARE)" },
  { name: "TOMMY HILFIGER" },
  { name: "Tosha International" },
  { name: "TOXSL Technologies PVT. LTD." },
  { name: "Trifid Research" },
  { name: "TRIFID Research Pvt. Ltd." },
  { name: "TRIGENT SOFTWARE" },
  { name: "Trigent Software Ltd." },
  { name: "Trimax Infrastrture and Services Ltd." },
  { name: "Trinity Global Tech Inc. (Off Campus)" },
  { name: "UAS International" },
  { name: "UGT INDIA PVT. LTD." },
  { name: "Uncease Group" },
  { name: "Unicommerce.com" },
  { name: "Uniparts India Ltd." },
  { name: "University 18" },
  { name: "Usha Power Tec" },
  { name: "V4 Solutions" },
  { name: "VAYAM TECHNOLOGIES LTD." },
  { name: "VEE LANCER ENGINEERING SERVICES" },
  { name: "Vermeer India" },
  { name: "Vertical Recruiters" },
  { name: "Vgyan Communication Pvt. Ltd." },
  { name: "VIP Industries Ltd. (Off Campus)" },
  { name: "Vishwakarma Scales" },
  { name: "VIVO Mobile" },
  { name: "VOICE TREE" },
  { name: "Voivo Infotech Pvt. Ltd." },
  { name: "Vserv Business Solutions Pvt. Ltd." },
  { name: "WEB EXPERT" },
  { name: "Webkul Software Pvt. Ltd." },
  { name: "Whiztech Labs Pvt. Ltd" },
  { name: "XL DYNAMICS" },
  { name: "Yes Bank" },
  { name: "Zeal Dream Homes Pvt. Ltd. " },
  { name: "Zenfocus Software Pvt. Ltd." },
  { name: "Zven Technologies Pvt. Ltd." },
];
